Kyligence/calcite

- cassandra/pom.xml
- core/pom.xml
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- linq4j/src/main/java/org/apache/calcite/linq4j/tree/BlockBuilder.java
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
#6546 fix NPE in cast nullable value into big decimal
> #6546 fix NPE in cast nullable value into big decimal

- core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
#4037 support implicit type convert in filters for '=' in particular
> #4037 support implicit type convert in filters for '=' in particular

- linq4j/src/main/java/org/apache/calcite/linq4j/tree/BlockBuilder.java
https://github.com/Kyligence/KAP/issues/7323
> #7323 fix generated code not compilable if the two sides of the join are simmilar

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java
- druid/pom.xml
- elasticsearch/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- linq4j/pom.xml
- linq4j/src/main/java/org/apache/calcite/linq4j/tree/BlockBuilder.java
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
#5417 merge atopcalcite to kycalcaite, and discard atopcalcite
> #5417 merge atopcalcite to kycalcaite, and discard atopcalcite

- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
https://github.com/Kyligence/KAP/issues/11944 fix query whose join condition has date column equals a constant
> #11944 fix query whose join condition has date column equals a constant

- core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
- core/src/main/java/org/apache/calcite/util/CancelFlag.java
> KE12016 Planner cancel flag 1.16.0.x

- core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
- core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java
- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
> KE12595  Detect cycles 

- linq4j/src/main/java/org/apache/calcite/linq4j/tree/BlockBuilder.java
Related issue: Kyligence/KAP#12810
> KE12810 make divide/multiply/plus/minus exp simple

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfig.java
- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfigImpl.java
- core/src/main/java/org/apache/calcite/config/CalciteConnectionProperty.java
- core/src/main/java/org/apache/calcite/prepare/Prepare.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
https://github.com/Kyligence/KAP/issues/10964 put project under relroot to fix async query
> #10964 put project under relroot to fix async query

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/sql/SqlDataTypeSpec.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
> #48 NEWTEN-12975 Remove charset during sql unparse

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rel/rules/OLAPJoinPushThroughJoinRule.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
> #12801, fix use error join type

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactory.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
- core/src/main/java/org/apache/calcite/sql/type/SqlOperandTypeChecker.java
- core/src/main/java/org/apache/calcite/sql/type/SqlTypeFactoryImpl.java
- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
https://github.com/Kyligence/KAP/issues/13872 comparison between char types should ignore right white space
> #13872 comparison between char types should ignore right white space

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/adapter/enumerable/ReflectiveCallNotNullImplementor.java
- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfig.java
- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfigImpl.java
- core/src/main/java/org/apache/calcite/config/CalciteConnectionProperty.java
- core/src/main/java/org/apache/calcite/prepare/CalciteCatalogReader.java
- core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java
- core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
https://github.com/Kyligence/KAP/issues/13473
#13473 return null not throw exception if zero is divided
> #13473 return null not throw exception if zero is divided

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystemImpl.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
related KAP issue : Kyligence/KAP#14074
> #58 change  timestamp default precision

- cassandra/pom.xml
- core/pom.xml
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- linq4j/src/main/java/org/apache/calcite/linq4j/tree/BlockBuilder.java
- linq4j/src/main/java/org/apache/calcite/linq4j/tree/Expressions.java
- linq4j/src/test/java/org/apache/calcite/linq4j/test/BlockBuilderTest.java
- linq4j/src/test/java/org/apache/calcite/linq4j/test/ExpressionTest.java
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
https://github.com/Kyligence/KAP/issues/14695
Join of two views with window aggregates produces null
[CALCITE-2271]
> #14695 Join of two views with window aggregates produces null

- core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
- core/src/main/java/org/apache/calcite/sql/type/NotConstant.java
…nctions that optimize the inheritance of specific interfaces
> Kap#65 Calcite ReduceExpressionsRule supports ignoring constant parameter functions that optimize the inheritance of specific interfaces 

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
https://github.com/Kyligence/KAP/issues/14734 fix query contains PI
> #14734 fix query contains PI

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
#10707 fix query like floor(mod())
https://github.com/Kyligence/KAP/issues/10707
> #10707 fix query like floor(mod())

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfigImpl.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
https://github.com/Kyligence/KAP/pull/13152
> #13152 support KylinOperatorTable

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rel/rules/AggregateReduceFunctionsRule.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
#15261 fix sum expression has inner aggregation
> #15261 fix sum expression has inner aggregation

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
> #11972,  fix join reduce

- pom.xml
> minor, add local nexus

- pom.xml
This reverts commit ea8771cbf3a51f1ab6e721d374fa70d600a75ba7.
> Revert "minor, add local nexus"

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/test/RexImplicationCheckerTest.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
[CALCITE-2334] Extend simplification of expressions with CEIL function over date types
Close apache/calcite#705
> KE-14058 fix bug of ceil/floor functions for timestamp(#705)

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rel/rules/AggregateReduceFunctionsRule.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
private isReducible  => protected isReducible
> KE-14512 Fix avg(col_1) can't work with sum(case when col_2 then col_1)

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
cherry-picked from https://github.com/Kyligence/calcite/commit/1deb9e4b11dee29cce4ca84676e8039400657e99
> KE-14593 assume date and timestamp are comparable 

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfig.java
- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfigImpl.java
- core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
…ade to r45 (#159)"
This reverts commit 05a3318a293995f0fdb6bdc4d96fe5270f3333cd.
> Revert KE-14627 make constant folding in project configured

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
KE-18456, fix out of range when substring
> KE-18456, fix out of range when substring

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/runtime/HttpUtils.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
see  https://github.com/apache/calcite/commit/43eeafcbac29d02c72bd520c003cdfc571de2d15
> KE 20343 correct ssl verf

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/test/RexProgramTest.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
> KE-18456, optimize SimplifyFilter

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/test/RexProgramTest.java
> KE-20665, code format

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
* Change RelToSqlConverter#subQueryList from LinkedHashSet to ArrayList
* Compare SubQuery by it's node reference, this ensures we get the node
from exact the scope where it belongs
* For SqlToRelConverter#getRootField, returns null if there is no field
matching the passed in input ref, because the input is not always a join
node; also remove the useless check for input row type null check
> [CALCITE-3456] AssertionError throws for aggregation with same digest IN subqueries in same scope

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/sql/fun/SqlCastFunction.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
> Revert "KE-29309 derive case when return type remove null literal"

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
This reverts commit ef6a4bed129ceae218952c1e7e85091aee6f9b94.
update calcite version to r017
> Revert "AL-4669 fix date cannot compare with string (#263)"

- cassandra/pom.xml
- core/pom.xml
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- druid/pom.xml
- elasticsearch2/pom.xml
- elasticsearch5/pom.xml
- example/csv/pom.xml
- example/function/pom.xml
- example/pom.xml
- file/pom.xml
- geode/pom.xml
- linq4j/pom.xml
- mongodb/pom.xml
- pig/pom.xml
- piglet/pom.xml
- plus/pom.xml
- pom.xml
- server/pom.xml
- spark/pom.xml
- splunk/pom.xml
- ubenchmark/pom.xml
> Revert "KE-33345 4.5"
